Repository slab/quill, pull requests merged in 2024-05, with the labels that each got.

#4127 Fix typing errors for Quill.register
  packages/quill/src/core.ts
  packages/quill/src/core/quill.ts
  packages/quill/src/modules/syntax.ts
  packages/quill/src/quill.ts
  packages/quill/test/types/quill.test-d.ts
  packages/quill/test/unit/core/quill.spec.ts
Labels: change:bugfix

#4198 Use labels for changelog generating
  .github/release.yml
  .github/workflows/label.yml
Labels: change:chore

#4199 Regenerate CHANGELOG from GitHub releases
  .github/workflows/changelog.yml
  CHANGELOG.md
  package-lock.json
  package.json
  scripts/changelog.mjs
  scripts/release.js
Labels: change:chore

#4200 Fix event source when deleting a link with shortcuts
  packages/quill/src/core/module.ts
  packages/quill/src/modules/toolbar.ts
  packages/quill/src/themes/bubble.ts
  packages/quill/src/themes/snow.ts
Labels: change:bugfix

#4201 Avoid side effects for Enter/Backspace when composing in Safari
  packages/quill/src/modules/keyboard.ts
Labels: change:bugfix

#4202 Ignore pasting images when image format is disallowed
  packages/quill/src/modules/uploader.ts
Labels: change:bugfix

#4203 Upgrade Node.js to 20 for CI
  .github/workflows/_test.yml
  .github/workflows/changelog.yml
  .github/workflows/release.yml
Labels: change:chore

#4219 Fixed a few typos in docs/installation.mdx
  packages/website/content/docs/installation.mdx
Labels: change:documentation

#4220 Export Delta, AttributeMap and other related objects
  packages/quill/src/quill.ts
  packages/quill/test/types/quill.test-d.ts
Labels: change:bugfix

#4225 Move Quill to Slab organization
  .github/CONTRIBUTING.md
  CHANGELOG.md
  README.md
  package.json
  packages/quill/package.json
  packages/quill/test/e2e/list.spec.ts
  packages/website/env.js
  packages/website/src/components/GitHub.jsx
  packages/website/src/components/Header.jsx
  packages/website/src/pages/index.jsx
  scripts/changelog.mjs
Labels: change:chore
